version: '3.5'

services:
  server-pool:
    container_name: ServerPool
    build:
      context: Server-Pool
    expose:
      - 8080
    networks:
      - internet
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_CONFIG_FILE=/root/.aws/config
    volumes:
      - $HOME/.aws/credentials:/root/.aws/config:ro

  load-balancer:
    container_name: LoadBalancer
    build:
      context: Load-Balancer
    ports:
      - 8080
    networks:
      - internet
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_CONFIG_FILE=/root/.aws/config
    volumes:
      - $HOME/.aws/credentials:/root/.aws/config:ro
    depends_on:
      - server-pool

  request-spawner:
    container_name: RequestSpawner
    build:
      context: Request-Spawner
    expose:
      - 8080
    networks:
      - internet
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_CONFIG_FILE=/root/.aws/config
    volumes:
      - $HOME/.aws/credentials:/root/.aws/config:ro
    depends_on:
      - load-balancer

networks:
  internet:
    driver: bridge
