version: '3.5'

x-common-variables: &aws-config
   AWS_DEFAULT_REGION: us-west-2
   AWS_CONFIG_FILE: /root/.aws/config
   SQS_PREFIX: ilb-
   SERVER_POOL_SNS: server-pool
   LOAD_BALANCER_SNS: load-balancer
   REQUEST_SPAWNER_SNS: request-spawner
   PRODUCTION: "True"

services:
  server-pool:
    container_name: ServerPool
    build:
      context: Server-Pool
    stdin_open: true
    tty: true
    environment: *aws-config
    volumes:
      - $HOME/.aws/credentials:/root/.aws/config:ro

  request-spawner:
    container_name: RequestSpawner
    build:
      context: Request-Spawner
    stdin_open: true
    tty: true
    environment: *aws-config
    volumes:
      - $HOME/.aws/credentials:/root/.aws/config:ro
    depends_on:
      - server-pool

  load-balancer:
    container_name: LoadBalancer
    build:
      context: Load-Balancer
    stdin_open: true
    tty: true
    environment: *aws-config
    volumes:
      - $HOME/.aws/credentials:/root/.aws/config:ro
    depends_on:
      - request-spawner
